# Pandas: Analysing Tabular Data
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Danselem/brics_astro/blob/main/Week2/02_pandas.ipynb)

# Pandas：分析表格数据

Welcome to a new tool in your Python arsenal: **Pandas**. While NumPy is excellent for working with arrays of numbers, astronomical data often comes in structured tables – like star catalogues, observation logs, or exoplanet databases. These tables usually have different types of data in different columns (text names, numerical values, dates, etc.) and helpful labels for both columns and rows.

欢迎使用 Python 库中的新工具：**Pandas**。虽然 NumPy 非常适合处理数字数组，但天文数据通常出现在结构化表格中，例如恒星目录、观测日志或系外行星数据库。这些表通常在不同的列中具有不同类型的数据（文本名称、数值、日期等）以及列和行的有用标签。

Pandas is a powerful library built specifically for handling and analysing this kind of structured, tabular data. Its main data structure, the **DataFrame**, is like a super-powered spreadsheet or a database table right within your Python code.

Pandas 是一个功能强大的库，专门用于处理和分析这种结构化的表格数据。它的主要数据结构 **DataFrame**，就像 Python 代码中的超级电子表格或数据库表。

This notebook will introduce you to the basics of using Pandas DataFrames to work with astronomical tables, making data cleaning, analysis, and exploration much more intuitive and efficient.

本笔记本将向您介绍使用 Pandas DataFrames 处理天文表的基础知识，使数据清理、分析和探索更加直观和高效。

**Learning Objectives:**

**学习目标：**

*   Understand what Pandas is and why it's useful for tabular data.
*   Learn about the core Pandas data structure: the DataFrame.
*   Create DataFrames from various sources.
*   Access and select columns and rows in a DataFrame.
*   Filter DataFrames based on conditions.
*   Perform basic operations and calculations on DataFrame columns.
*   Read data into DataFrames from local files (CSV).
*   Read data into DataFrames directly from online sources (URLs).
*   Handle simple cases of missing data.

* 了解 Pandas 是什么以及为什么它对表格数据有用。
* 了解 Pandas 的核心数据结构：DataFrame。
* 从各种来源创建数据帧。
* 访问并选择 DataFrame 中的列和行。
* 根据条件过滤数据帧。
* 对 DataFrame 列执行基本操作和计算。
* 从本地文件 (CSV) 将数据读入 DataFrame。
* 直接从在线源 (URL) 将数据读入 DataFrame。
* 处理丢失数据的简单情况。

**Prerequisites:**

**先决条件：**

*   Basic familiarity with Python syntax (variables, data types, lists, dictionaries).
*   Basic understanding of NumPy arrays.
*   Familiarity with Jupyter Notebooks.

* 基本熟悉Python语法（变量、数据类型、列表、字典）。
* 对 NumPy 数组的基本了解。
* 熟悉 Jupyter Notebook。

**Key Terms:**

**关键术语：**

*   **Pandas:** A Python library for data analysis and manipulation.
*   **DataFrame:** A 2-dimensional labelled data structure with columns of potentially different types. Like a spreadsheet or table.
*   **Series:** A 1-dimensional labelled array. Each column in a DataFrame is a Series.
*   **Index:** The labels for the rows in a DataFrame.
*   **Column:** A vertical sequence of data in a DataFrame, usually representing a specific attribute (e.g., 'Name', 'Mass', 'Temperature').
*   **CSV:** Comma-Separated Values. A common text file format for storing tabular data.

* **Pandas：** 用于数据分析和操作的 Python 库。
* **DataFrame：** 二维标记数据结构，其中包含可能不同类型的列。就像电子表格或表格一样。
* **系列：** 一维标记数组。 DataFrame 中的每一列都是一个 Series。
* **索引：** DataFrame 中行的标签。
* **列：** DataFrame 中的垂直数据序列，通常表示特定属性（例如“名称”、“质量”、“温度”）。
* **CSV:** 逗号分隔值。用于存储表格数据的常见文本文件格式。

**Note**
If you are running this jupyter notebook from Colab, then run the next cell by pressing `SHIFT+ENTER` to install the required packages for this notebook. Otherwise, skip the next cell.

**注意**
如果您从 Colab 运行此 jupyter 笔记本，请按 `SHIFT+ENTER` 运行下一个单元以安装此笔记本所需的软件包。否则，跳过下一个单元格。

In [ ]:
!pip install numpy pandas matplotlib

## What is Pandas and the DataFrame（什么是 Pandas 和 DataFrame）

Imagine you have data like this:

想象一下你有这样的数据：

```code
Name        | Type      | Distance (light-years)
---         | ---       | ---
Andromeda   | Spiral    | 2.537 million
Milky Way   | Spiral    | 0 (our galaxy)
Triangulum  | Spiral    | 3.0 million
Large Magellanic Cloud | Irregular | 0.16 million
```

名称 |类型 |距离（光年）
--- | --- | ---
仙女座 |螺旋| 253.7万
银河 |螺旋| 0（我们的银河系）
三角|螺旋| 300万
大麦哲伦星云 |不规则 | 16万

In Python lists, you might store this as lists within lists:

在 Python 列表中，您可以将其存储为列表中的列表：

In [1]:
galaxies_list = [
    ['Andromeda', 'Spiral', 2.537],
    ['Milky Way', 'Spiral', 0.0],
    ['Triangulum', 'Spiral', 3.0],
    ['Large Magellanic Cloud', 'Irregular', 0.16]
]

# Or maybe a list of dictionaries:
galaxies_list_of_dicts = [
    {'Name': 'Andromeda', 'Type': 'Spiral', 'Distance_mly': 2.537},
    {'Name': 'Milky Way', 'Type': 'Spiral', 'Distance_mly': 0.0},
    {'Name': 'Triangulum', 'Type': 'Spiral', 'Distance_mly': 3.0},
    {'Name': 'Large Magellanic Cloud', 'Type': 'Irregular', 'Distance_mly': 0.16}
]

These work, but performing operations (like finding the average distance of only Spiral galaxies)
can become complex with nested loops and conditional logic.

这些工作，但是执行操作（例如仅查找螺旋星系的平均距离）
嵌套循环和条件逻辑可能会变得复杂。

Pandas provides the DataFrame, which is much better suited for this:

Pandas 提供了 DataFrame，它更适合于此：

In [41]:
import pandas as pd # Standard way to import Pandas

# Creating a DataFrame from our list of dictionaries:
galaxies_df = pd.DataFrame(galaxies_list_of_dicts)

# Printing the DataFrame:
print("Our Galaxies DataFrame:")
galaxies_df

Our Galaxies DataFrame:

                     Name       Type  Distance_mly
0               Andromeda     Spiral         2.537
1               Milky Way     Spiral         0.000
2              Triangulum     Spiral         3.000
3  Large Magellanic Cloud  Irregular         0.160

Notice how it's structured with column names and row numbers (the index).
This makes working with the data much easier!

请注意它是如何使用列名和行号（索引）来构造的。
这使得数据处理变得更加容易！

## Creating DataFrames（创建数据框）

The most common ways to create a DataFrame are:

创建 DataFrame 最常见的方法是：

1.  **From a Dictionary:** Where keys are column names and values are lists or NumPy arrays of data for those columns. This is often the easiest way to start with small datasets you define in your code.
2.  **From a List of Dictionaries:** Each dictionary represents a row.
3.  **From Files:** Reading data from CSV, Excel, JSON files, etc.
4.  **From Online Sources:** Reading directly from URLs.

1. **来自字典：** 其中键是列名称，值是这些列的数据列表或 NumPy 数组。这通常是从您在代码中定义的小型数据集开始的最简单方法。
2. **来自字典列表：** 每个字典代表一行。
3. **从文件：** 从 CSV、Excel、JSON 文件等读取数据。
4. **来自在线资源：** 直接从 URL 读取。

We'll focus on the dictionary method first, then move to files and URLs.

我们将首先关注字典方法，然后转向文件和 URL。

### Example 1: Creating a DataFrame from a Dictionary（示例 1：从字典创建 DataFrame）

Data for some bright stars: Name, Spectral Type, Apparent Magnitude

一些明亮恒星的数据：名称、光谱类型、视星等

In [42]:
star_data_dict = {
    'Name': ['Sirius', 'Canopus', 'Alpha Centauri', 'Arcturus'],
    'Spectral_Type': ['A1V', 'F0', 'G2V', 'K1.5III'],
    'Apparent_Magnitude': [-1.46, -0.72, -0.27, -0.04]
}

# Create the DataFrame
bright_stars_df = pd.DataFrame(star_data_dict)

print("DataFrame created from dictionary:")
bright_stars_df

DataFrame created from dictionary:

             Name Spectral_Type  Apparent_Magnitude
0          Sirius           A1V               -1.46
1         Canopus            F0               -0.72
2  Alpha Centauri           G2V               -0.27
3        Arcturus       K1.5III               -0.04

Each key in the dictionary becomes a column name.
The lists become the data in those columns.
Pandas automatically adds a numerical index (0, 1, 2, 3) for the rows.

字典中的每个键都成为一个列名。
列表成为这些列中的数据。
Pandas 自动为行添加数字索引 (0, 1, 2, 3)。

## Accessing and Selecting Data（访问和选择数据）

Once you have a DataFrame, you need to be able to select specific columns, rows, or even individual values.

拥有 DataFrame 后，您需要能够选择特定的列、行，甚至单个值。

*   **Selecting Columns:** You can select one or more columns using their names.
*   **Selecting Rows:** You can select rows using their index label (`.loc`) or their integer position (`.iloc`).
*   **Selecting Specific Cells:** Combine row and column selection.

* **选择列：** 您可以使用名称选择一个或多个列。
* **选择行：** 您可以使用索引标签 (`.loc`) 或其整数位置 (`.iloc`) 选择行。
* **选择特定单元格：** 组合行和列选择。

### Example 2: Selecting Columns（示例 2：选择列）

Using our bright_stars_df from Example 1

使用示例 1 中的 Bright_stars_df

In [43]:
print("Original DataFrame:")
bright_stars_df

Original DataFrame:

             Name Spectral_Type  Apparent_Magnitude
0          Sirius           A1V               -1.46
1         Canopus            F0               -0.72
2  Alpha Centauri           G2V               -0.27
3        Arcturus       K1.5III               -0.04

In [44]:
# Select a single column:
# Result is a Pandas Series (a 1D labeled array)
star_names = bright_stars_df['Name'] # Use column name like a dictionary key
print("\nSelecting the 'Name' column:")
print(star_names)
print("Type of selected column:", type(star_names)) # It's a Series

Selecting the 'Name' column:
0            Sirius
1           Canopus
2    Alpha Centauri
3          Arcturus
Name: Name, dtype: object
Type of selected column: <class 'pandas.core.series.Series'>

In [6]:
# Select multiple columns:
# Pass a list of column names. Result is a DataFrame.
names_and_magnitudes = bright_stars_df[['Name', 'Apparent_Magnitude']] # Use a LIST of names
print("\nSelecting 'Name' and 'Apparent_Magnitude' columns:")
print(names_and_magnitudes)
print("Type of selected columns:", type(names_and_magnitudes)) # It's a DataFrame

Selecting 'Name' and 'Apparent_Magnitude' columns:
             Name  Apparent_Magnitude
0          Sirius               -1.46
1         Canopus               -0.72
2  Alpha Centauri               -0.27
3        Arcturus               -0.04
Type of selected columns: <class 'pandas.core.frame.DataFrame'>

### Example 3: Selecting Rows with .loc and .iloc（示例 3：选择带有 .loc 和 .iloc 的行）

Using our bright_stars_df

使用我们的 Bright_stars_df

In [45]:
print("Original DataFrame:")
bright_stars_df

Original DataFrame:

             Name Spectral_Type  Apparent_Magnitude
0          Sirius           A1V               -1.46
1         Canopus            F0               -0.72
2  Alpha Centauri           G2V               -0.27
3        Arcturus       K1.5III               -0.04

In [8]:
# Select a row by its label using .loc
# The default labels are the integer index (0, 1, 2, ...)
sirius_row = bright_stars_df.loc[0] # Get the row with index label 0
print("\nSelecting row with label 0 (Sirius) using .loc:")
print(sirius_row)
print("Type of selected row:", type(sirius_row)) # It's a Series

Selecting row with label 0 (Sirius) using .loc:
Name                  Sirius
Spectral_Type            A1V
Apparent_Magnitude     -1.46
Name: 0, dtype: object
Type of selected row: <class 'pandas.core.series.Series'>

In [46]:
# Select a row by its integer position using .iloc
# This is just like list/NumPy array indexing
canopus_row = bright_stars_df.iloc[1] # Get the row at integer position 1
print("\nSelecting row at position 1 (Canopus) using .iloc:")
canopus_row

Selecting row at position 1 (Canopus) using .iloc:

Name                  Canopus
Spectral_Type              F0
Apparent_Magnitude      -0.72
Name: 1, dtype: object

In [10]:
# Select multiple rows using slicing with .loc (uses labels)
first_two_stars_loc = bright_stars_df.loc[0:1] # Includes label 1! (Unlike Python list slicing)
print("\nSelecting rows with labels 0 to 1 (Sirius and Canopus) using .loc[0:1]:")
print(first_two_stars_loc)

Selecting rows with labels 0 to 1 (Sirius and Canopus) using .loc[0:1]:
      Name Spectral_Type  Apparent_Magnitude
0   Sirius           A1V               -1.46
1  Canopus            F0               -0.72

In [11]:
# Select multiple rows using slicing with .iloc (uses positions)
first_two_stars_iloc = bright_stars_df.iloc[0:2] # Excludes position 2 (Like Python list slicing)
print("\nSelecting rows at positions 0 and 1 (Sirius and Canopus) using .iloc[0:2]:")
print(first_two_stars_iloc)

Selecting rows at positions 0 and 1 (Sirius and Canopus) using .iloc[0:2]:
      Name Spectral_Type  Apparent_Magnitude
0   Sirius           A1V               -1.46
1  Canopus            F0               -0.72

### Example 4: Selecting Specific Cells（示例 4：选择特定单元格）

In [12]:
# Using our bright_stars_df
print("Original DataFrame:")
print(bright_stars_df)

# Select a specific value (Sirius's magnitude) using .loc[row_label, column_label]
sirius_mag = bright_stars_df.loc[0, 'Apparent_Magnitude']
print("\nSirius's magnitude using .loc[0, 'Apparent_Magnitude']:", sirius_mag)

Original DataFrame:
             Name Spectral_Type  Apparent_Magnitude
0          Sirius           A1V               -1.46
1         Canopus            F0               -0.72
2  Alpha Centauri           G2V               -0.27
3        Arcturus       K1.5III               -0.04

Sirius's magnitude using .loc[0, 'Apparent_Magnitude']: -1.46

In [47]:
# Select a specific value (Canopus's Spectral Type) using .iloc[row_position, column_position]
canopus_spectral_type = bright_stars_df.iloc[1, 1]
print("Canopus's Spectral Type using .iloc[1, 1]:", canopus_spectral_type)

# Selecting a slice of rows and a slice of columns
some_data = bright_stars_df.loc[1:2, ['Name', 'Apparent_Magnitude']]
print("\nSelecting subset of rows and columns:")
some_data

Canopus's Spectral Type using .iloc[1, 1]: F0

Selecting subset of rows and columns:

             Name  Apparent_Magnitude
1         Canopus               -0.72
2  Alpha Centauri               -0.27

## Filtering DataFrames（过滤数据框）

A very common task is to select only the rows that meet certain criteria. Pandas makes this easy using boolean indexing, similar to NumPy. You create a condition that results in a Series of `True`/`False` values, and then use this Series to select the rows where the condition is `True`.

一个非常常见的任务是仅选择满足特定条件的行。 Pandas 使用布尔索引使这一切变得容易，类似于 NumPy。您创建一个条件，该条件会产生一系列`True`/`False` 值，然后使用该系列选择条件为`True` 的行。

### Example 5: Filtering Rows（示例 5：过滤行）

In [14]:
# Using our bright_stars_df
print("Original DataFrame:")
print(bright_stars_df)

# Condition 1: Find stars that are brighter than magnitude 0.0 (smaller number = brighter)
is_brighter_than_0 = bright_stars_df['Apparent_Magnitude'] < 0.0
print("\nBoolean Series for stars brighter than 0.0:")
print(is_brighter_than_0)

Original DataFrame:
             Name Spectral_Type  Apparent_Magnitude
0          Sirius           A1V               -1.46
1         Canopus            F0               -0.72
2  Alpha Centauri           G2V               -0.27
3        Arcturus       K1.5III               -0.04

Boolean Series for stars brighter than 0.0:
0    True
1    True
2    True
3    True
Name: Apparent_Magnitude, dtype: bool

In [15]:
# Use the boolean Series to filter the DataFrame
very_bright_stars_df = bright_stars_df[is_brighter_than_0]
print("\nDataFrame filtered for stars brighter than 0.0:")
print(very_bright_stars_df)

# Condition 2: Find stars that are Spectral Type 'G2V'
is_spectral_type_G2V = bright_stars_df['Spectral_Type'] == 'G2V'
print("\nBoolean Series for stars with Spectral Type 'G2V':")
print(is_spectral_type_G2V)

DataFrame filtered for stars brighter than 0.0:
             Name Spectral_Type  Apparent_Magnitude
0          Sirius           A1V               -1.46
1         Canopus            F0               -0.72
2  Alpha Centauri           G2V               -0.27
3        Arcturus       K1.5III               -0.04

Boolean Series for stars with Spectral Type 'G2V':
0    False
1    False
2     True
3    False
Name: Spectral_Type, dtype: bool

In [48]:
# Filter using the condition directly (common shorthand)
G2V_stars_df = bright_stars_df[bright_stars_df['Spectral_Type'] == 'G2V']
print("\nDataFrame filtered for Spectral Type 'G2V':")
G2V_stars_df

DataFrame filtered for Spectral Type 'G2V':

             Name Spectral_Type  Apparent_Magnitude
2  Alpha Centauri           G2V               -0.27

You can combine multiple conditions using logical operators:

您可以使用逻辑运算符组合多个条件：

```code
&  (AND)
|  (OR)
~  (NOT)
```

&（与）
|  （或）
〜（不）

**IMPORTANT:** Each condition must be enclosed in parentheses `()`

**重要：** 每个条件都必须括在括号中`()`

### Example 6: Filtering with Multiple Conditions（示例 6：使用多个条件进行过滤）

In [49]:
# Find stars that are brighter than 0.0 AND have Spectral Type 'A1V'
bright_and_A1V = (bright_stars_df['Apparent_Magnitude'] < 0.0) & (bright_stars_df['Spectral_Type'] == 'A1V')
filtered_df = bright_stars_df[bright_and_A1V]
print("Stars brighter than 0.0 AND Spectral Type 'A1V':")
filtered_df

Stars brighter than 0.0 AND Spectral Type 'A1V':

     Name Spectral_Type  Apparent_Magnitude
0  Sirius           A1V               -1.46

In [50]:
# Find stars that are Spectral Type 'F0' OR Spectral Type 'K1.5III'
F0_or_K_stars = (bright_stars_df['Spectral_Type'] == 'F0') | (bright_stars_df['Spectral_Type'] == 'K1.5III')
filtered_df_or = bright_stars_df[F0_or_K_stars]
print("\nStars with Spectral Type 'F0' OR 'K1.5III':")
filtered_df_or

Stars with Spectral Type 'F0' OR 'K1.5III':

       Name Spectral_Type  Apparent_Magnitude
1   Canopus            F0               -0.72
3  Arcturus       K1.5III               -0.04

## Basic Operations and Adding New Columns（基本操作和添加新列）

You can perform mathematical operations on entire columns (Series) directly. You can also easily add new columns to your DataFrame, often based on calculations from existing columns.

您可以直接对整个列（系列）执行数学运算。您还可以轻松地向 DataFrame 添加新列，通常基于现有列的计算。

### Example 7: Operations and Adding Columns（示例 7：操作和添加列）

In [51]:
# Using our bright_stars_df
print("Original DataFrame:")
bright_stars_df

Original DataFrame:

             Name Spectral_Type  Apparent_Magnitude
0          Sirius           A1V               -1.46
1         Canopus            F0               -0.72
2  Alpha Centauri           G2V               -0.27
3        Arcturus       K1.5III               -0.04

Add a new column for Absolute Magnitude (simplified calculation)

添加新列“绝对幅度”（简化计算）

`Absolute Magnitude (M) = Apparent Magnitude (m) - 5 * log10(distance in parsecs / 10)`

@@内联0@@

Let's assume some hypothetical distances in parsecs for these stars

让我们假设这些恒星的一些假设距离（秒差距）

In [53]:
distances_pc = pd.Series([1.34, 99.0, 1.34, 11.0]) # Create a Series with distances
bright_stars_df['Distance_pc'] = distances_pc # Add this Series as a new column

In [54]:
# Now calculate Absolute Magnitude
# Need numpy for log10
import numpy as np

bright_stars_df['Absolute_Magnitude'] = bright_stars_df['Apparent_Magnitude'] - 5 * np.log10(bright_stars_df['Distance_pc'] / 10)

print("\nDataFrame after adding 'Distance_pc' and 'Absolute_Magnitude' columns:")
bright_stars_df

DataFrame after adding 'Distance_pc' and 'Absolute_Magnitude' columns:

,Name,Spectral_Type,Apparent_Magnitude,Distance_pc,Absolute_Magnitude
0,Sirius,A1V,-1.46,1.34,2.904476
1,Canopus,F0,-0.72,99.00,-5.698176
2,Alpha Centauri,G2V,-0.27,1.34,4.094476
3,Arcturus,K1.5III,-0.04,11.00,-0.246963

In [55]:
# Calculate the average Apparent Magnitude
average_apparent_mag = bright_stars_df['Apparent_Magnitude'].mean() # Use .mean() method on the Series
print(f"\nAverage Apparent Magnitude: {average_apparent_mag:.2f}")

# Calculate the maximum Absolute Magnitude
max_absolute_mag = bright_stars_df['Absolute_Magnitude'].max()
print(f"Maximum Absolute Magnitude: {max_absolute_mag:.2f}")

Average Apparent Magnitude: -0.62
Maximum Absolute Magnitude: 4.09

## Reading Data from Files (CSV)（从文件中读取数据 (CSV)）

Real astronomical data often comes in files, especially CSV (Comma-Separated Values) files. Pandas provides the `pd.read_csv()` function, which is extremely useful for loading these files directly into a DataFrame.

真实的天文数据通常以文件形式出现，尤其是 CSV（逗号分隔值）文件。 Pandas 提供了 `pd.read_csv()` 函数，该函数对于将这些文件直接加载到 DataFrame 中非常有用。

### Example 8: Reading from a Local CSV File（示例 8：从本地 CSV 文件读取）

First, let's create a simple dummy CSV file named `exoplanet_data.csv` with some hypothetical data. You can create this file manually or run this code:

首先，让我们创建一个名为 `exoplanet_data.csv` 的简单虚拟 CSV 文件，其中包含一些假设数据。您可以手动创建此文件或运行此代码：

In [24]:
# Example 8: Reading from a Local CSV File

# First, let's create a simple dummy CSV file named 'exoplanet_data.csv'
# with some hypothetical data. You can create this file manually or run this code:
csv_content = """Name,Radius_Earth,OrbitalPeriod_days,Habitable
Kepler-186f,1.11,129.9,True
Kepler-1649b,1.06,8.68,False
TRAPPIST-1e,0.91,6.10,True
51 Pegasi b,1.50,4.23,False
"""
with open("exoplanet_data.csv", "w") as f:
    f.write(csv_content)

print("Created dummy file 'exoplanet_data.csv'")

Created dummy file 'exoplanet_data.csv'

In [25]:
# Now, read the CSV file into a DataFrame:
exoplanets_df = pd.read_csv("exoplanet_data.csv")

print("\nDataFrame read from 'exoplanet_data.csv':")
print(exoplanets_df)

# Check the data types Pandas inferred
print("\nInfo about the DataFrame:")
exoplanets_df.info()

DataFrame read from 'exoplanet_data.csv':
           Name  Radius_Earth  OrbitalPeriod_days  Habitable
0   Kepler-186f          1.11              129.90       True
1  Kepler-1649b          1.06                8.68      False
2   TRAPPIST-1e          0.91                6.10       True
3   51 Pegasi b          1.50                4.23      False

Info about the DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                4 non-null      object
 1   Radius_Earth        4 non-null      float64
 2   OrbitalPeriod_days  4 non-null      float64
 3   Habitable           4 non-null      bool
dtypes: bool(1), float64(2), object(1)
memory usage: 232.0+ bytes

## Reading Data from Online Sources (URLs)（从在线源 (URL) 读取数据）

One of the most powerful features of `pd.read_csv()` is its ability to read directly from a URL! If a CSV file is available online, you can pass its web address to `read_csv()`, and Pandas will download and load it for you. This is incredibly useful for accessing publicly available astronomical datasets.

`pd.read_csv()` 最强大的功能之一是它能够直接从 URL 读取！如果在线提供 CSV 文件，您可以将其网址传递给`read_csv()`，Pandas 将为您下载并加载该文件。这对于访问公开的天文数据集非常有用。

### Example 9: Reading from an Online CSV File (Exoplanet Archive Simplified Data)（示例 9：读取在线 CSV 文件（Exoplanet Archive 简化数据））

This is a URL pointing to a simplified CSV file often used in tutorials,
potentially representing a small subset of data from the NASA Exoplanet Archive or similar.
Note: Real URLs might change, and data providers might have APIs instead of static files.
This is a demonstration of the capability.

这是一个指向教程中经常使用的简化 CSV 文件的 URL，
可能代表来自 NASA 系外行星档案或类似数据的一小部分数据。
注意：真实 URL 可能会发生变化，并且数据提供者可能具有 API 而不是静态文件。
这是能力的体现。

In [31]:
exoplanet_url = "https://raw.githubusercontent.com/astroryan97/Exploring-Exoplanet-Data/main/open_exoplanet_catalogue.csv"

try:
    # Read the data directly from the URL
    online_exoplanets_df = pd.read_csv(exoplanet_url)

    print("DataFrame read from URL:")
    print(online_exoplanets_df.head()) # Print only the first few rows (head)
    print(f"\nTotal rows loaded: {len(online_exoplanets_df)}")

    # Let's do a quick check - how many rows have 'KOI' in the 'NAME' column?
    koi_planets = online_exoplanets_df[online_exoplanets_df['name'].str.contains('KOI', na=False)]
    print(f"\nNumber of KOI planets found: {len(koi_planets)}")


except Exception as e:
    print(f"Could not load data from the URL. Make sure the URL is correct and accessible.")
    print(f"Error details: {e}")

DataFrame read from URL:
           name  binaryflag    mass  radius     period  semimajoraxis  \
0   KOI-1843.03           0  0.0014   0.054   0.176891         0.0048
1  Kepler-974 b           0     NaN   0.140   4.194497         0.0390
2   KOI-1843.02           0     NaN   0.071   6.356006         0.0520
3    Kepler-9 b           0  0.2500   0.840  19.224180         0.1430
4    Kepler-9 c           0  0.1700   0.820  39.031060         0.2290

   eccentricity  periastron  longitude  ascendingnode  ...  lastupdate  \
0           NaN         NaN        NaN            NaN  ...    13/07/15
1           NaN         NaN        NaN            NaN  ...    17/11/28
2           NaN         NaN        NaN            NaN  ...         NaN
3        0.0626         NaN        NaN            NaN  ...    15/12/03
4        0.0684         NaN        NaN            NaN  ...    15/12/03

   system_rightascension  system_declination system_distance  hoststar_mass  \
0          19 00 03.1450      +40 13 14.7985         134.833           0.52
1          19 00 03.1450      +40 13 14.7985         134.833           0.52
2          19 00 03.1450      +40 13 14.7985         134.833           0.52
3          19 02 17.7544      +38 24 03.1772         650.000           1.07
4          19 02 17.7544      +38 24 03.1772         650.000           1.07

  hoststar_radius hoststar_metallicity hoststar_temperature  hoststar_age  \
0            0.50                 0.07               3687.0           NaN
1            0.50                 0.07               3687.0           NaN
2            0.50                 0.07               3687.0           NaN
3            1.02                 0.12               5777.0           NaN
4            1.02                 0.12               5777.0           NaN

                list
0      Controversial
1  Confirmed planets
2      Controversial
3  Confirmed planets
4  Confirmed planets

[5 rows x 25 columns]

Total rows loaded: 4493

Number of KOI planets found: 72

## Handling Missing Data（处理缺失数据）

Real-world data often has gaps or missing values. Pandas represents missing numerical values as `NaN` (Not a Number). You'll need to be able to detect and handle these missing values, either by removing rows/columns with missing data or filling them in.

现实世界的数据通常存在差距或缺失值。 Pandas 将缺失的数值表示为`NaN`（不是数字）。您需要能够通过删除缺少数据的行/列或填充它们来检测和处理这些缺失值。

### Example 10: Handling Missing Data（示例 10：处理缺失数据）

In [35]:
# Let's create a DataFrame with some missing values
data_with_missing = {
    'Object': ['Star A', 'Star B', 'Galaxy C', 'Star D'],
    'Magnitude': [2.1, 3.5, np.nan, 4.8], # np.nan represents a missing value
    'Redshift': [0.001, 0.002, 0.015, np.nan]
}
missing_df = pd.DataFrame(data_with_missing)

print("DataFrame with missing data:")
print(missing_df)

DataFrame with missing data:
     Object  Magnitude  Redshift
0    Star A        2.1     0.001
1    Star B        3.5     0.002
2  Galaxy C        NaN     0.015
3    Star D        4.8       NaN

In [36]:
# Check which values are missing
print("\nChecking for missing values (isnull()):")
print(missing_df.isnull()) # Returns True where data is missing

# Get a summary of missing values per column
print("\nMissing values per column:")
print(missing_df.isnull().sum())

Checking for missing values (isnull()):
   Object  Magnitude  Redshift
0   False      False     False
1   False      False     False
2   False       True     False
3   False      False      True

Missing values per column:
Object       0
Magnitude    1
Redshift     1
dtype: int64

In [37]:
# Option 1: Drop rows with *any* missing values
cleaned_df_dropped_rows = missing_df.dropna()
print("\nDataFrame after dropping rows with missing data:")
print(cleaned_df_dropped_rows)

DataFrame after dropping rows with missing data:
   Object  Magnitude  Redshift
0  Star A        2.1     0.001
1  Star B        3.5     0.002

In [38]:
# Option 2: Drop columns with *any* missing values
cleaned_df_dropped_cols = missing_df.dropna(axis=1) # axis=1 means columns
print("\nDataFrame after dropping columns with missing data:")
print(cleaned_df_dropped_cols)

DataFrame after dropping columns with missing data:
     Object
0    Star A
1    Star B
2  Galaxy C
3    Star D

In [39]:
# Option 3: Fill missing values (e.g., with a placeholder or mean)
filled_df = missing_df.fillna(value=0) # Fill NaN with 0
print("\nDataFrame after filling missing values with 0:")
print(filled_df)

DataFrame after filling missing values with 0:
     Object  Magnitude  Redshift
0    Star A        2.1     0.001
1    Star B        3.5     0.002
2  Galaxy C        0.0     0.015
3    Star D        4.8     0.000

In [40]:
# Fill missing magnitude with the mean magnitude (excluding NaN)
# mean() ignores NaN by default
mean_magnitude = missing_df['Magnitude'].mean()
filled_df_mean_mag = missing_df.fillna({'Magnitude': mean_magnitude})
print("\nDataFrame after filling missing Magnitude with mean:")
print(filled_df_mean_mag)

DataFrame after filling missing Magnitude with mean:
     Object  Magnitude  Redshift
0    Star A   2.100000     0.001
1    Star B   3.500000     0.002
2  Galaxy C   3.466667     0.015
3    Star D   4.800000       NaN

## Exercises（练习）

Time to practice your Pandas skills with astronomical data!

是时候用天文数据练习你的 Pandas 技能了！

1.  **Create a Small Catalog:** Create a DataFrame for three hypothetical stars with columns 'Name', 'Mass_Solar', and 'Radius_Solar'.
2.  **Select Mass Column:** From your star DataFrame, select and print only the 'Mass_Solar' column.
3.  **Select First Star:** Select and print the data for the first star using `.loc[0]`.
4.  **Select Name and Radius for Second Star:** Select and print *only* the name and radius for the second star using a combination of row and column selection.
5.  **Filter by Mass:** From your star DataFrame, filter and print only the stars with a mass greater than 1.0 Solar Mass.
6.  **Add Density Column (Bonus):** Add a new column named 'Density_Solar' (relative to the Sun). Density is Mass / Volume, and Volume is proportional to Radius^3. So, Density_Solar ≈ Mass_Solar / (Radius_Solar ** 3). Calculate this for each star and add it as a new column. Print the updated DataFrame.
7.  **Read Your Exoplanet CSV:** Load the 'exoplanet_data.csv' file you created in Example 8 back into a DataFrame.
8.  **Filter Habitable Planets:** From the 'exoplanet_data.csv' DataFrame, filter and print only the rows where the 'Habitable' column is `True`.
9.  **Calculate Average Radius:** Calculate and print the average 'Radius_Earth' for all exoplanets in the DataFrame loaded from 'exoplanet_data.csv'.
10. **Read Online Data:** (If Example 9 worked) Load the online exoplanet data again from the provided URL. Calculate the average 'RADIUS' for all planets in that online dataset.

1. **创建一个小目录：** 为三个假设的恒星创建一个 DataFrame，其中包含“Name”、“Mass_Solar”和“Radius_Solar”列。
2. **选择 Mass 列：** 从星型 DataFrame 中，仅选择并打印“Mass_Solar”列。
3. **选择第一颗星：** 使用`.loc[0]` 选择并打印第一颗星的数据。
4. **选择第二颗星的名称和半径：** 使用行和列选择的组合选择并*仅*打印第二颗星的名称和半径。
5. **按质量过滤：** 从您的恒星数据框中，仅过滤并打印质量大于 1.0 太阳质量的恒星。
6. **添加密度列（奖励）：** 添加一个名为“Density_Solar”的新列（相对于太阳）。密度为质量/体积，体积与半径^3 成正比。因此，Density_Solar ≈ Mass_Solar / (Radius_Solar ** 3)。计算每颗星星的值并将其添加为新列。打印更新后的 DataFrame。
7. **读取您的 Exoplanet CSV：** 将您在示例 8 中创建的“exoplanet_data.csv”文件加载回 DataFrame。
8. **过滤宜居行星：** 从“exoplanet_data.csv”数据框中，仅过滤并打印“宜居”列为`True` 的行。
9. **计算平均半径：** 计算并打印从“exoplanet_data.csv”加载的 DataFrame 中所有系外行星的平均值“Radius_Earth”。
10. **读取在线数据：**（如果示例 9 有效）从提供的 URL 再次加载在线系外行星数据。计算该在线数据集中所有行星的平均“半径”。

## Summary（概括）

You've now gained fundamental skills in using the Pandas library for handling and analysing tabular data! You've learned:

您现在已经获得了使用 Pandas 库处理和分析表格数据的基本技能！你已经学会了：

*   The DataFrame is the core structure for labelled, mixed-type data.
*   How to create DataFrames.
*   How to select columns, rows, and cells using labels (`.loc`) and positions (`.iloc`).
*   How to filter DataFrames based on single or multiple conditions.
*   How to perform operations and add new columns.
*   Crucially, how to read data into DataFrames from both local CSV files and online URLs.
*   How to identify and perform basic handling of missing data.

* DataFrame 是带标签的混合类型数据的核心结构。
* 如何创建数据框。
* 如何使用标签 (`.loc`) 和位置 (`.iloc`) 选择列、行和单元格。
* 如何根据单个或多个条件过滤DataFrame。
* 如何执行操作和添加新列。
* 至关重要的是，如何从本地 CSV 文件和在线 URL 将数据读入 DataFrame。
* 如何识别和执行缺失数据的基本处理。

Pandas is an essential tool in the data science toolkit and is widely used in astronomy. With these basics, you are well-equipped to start exploring, cleaning, and analysing real datasets. Keep practising!

Pandas 是数据科学工具包中的重要工具，广泛应用于天文学。有了这些基础知识，您就可以开始探索、清理和分析真实数据集了。继续练习！

**Additional Resources**

**额外资源**

Here are some resources for understanding `Pandas`

以下是一些用于理解`Pandas`的资源

Getting started with Pandas: <https://pandas.pydata.org/docs/getting_started/index.html#getting-started>

熊猫入门：<https://pandas.pydata.org/docs/getting_started/index.html#getting-started>

Pandas user guide: <https://pandas.pydata.org/docs/user_guide/index.html#user-guide>

熊猫用户指南：<https://pandas.pydata.org/docs/user_guide/index.html#user-guide>

Groupby with Pandas: <https://realpython.com/pandas-groupby/>

与熊猫分组：<https://realpython.com/pandas-groupby/>

Handling big data with pandas: <https://www.scaler.com/topics/pandas/handling-large-datasets-in-pandas/>

用 pandas 处理大数据：<https://www.scaler.com/topics/pandas/handling-large-datasets-in-pandas/>

How to handle parquet data files: <https://www.datacamp.com/tutorial/apache-parquet>

如何处理镶木地板数据文件：<https://www.datacamp.com/tutorial/apache-parquet>

Introduction to Polars: <https://www.datacamp.com/blog/an-introduction-to-polars-python-s-tool-for-large-scale-data-analysis>

极地简介：<https://www.datacamp.com/blog/an-introduction-to-polars-python-s-tool-for-large-scale-data-analysis>